services:
  labseq-api:
    image: labseq-api-img
    container_name: labseq-api
    build:
      context: labseq
    ports:
      - "8085:8085"
    networks:
      - labseq-network
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - labseq-network
  labseq-ui:
    image: labseq-ui-img
    container_name: labseq-ui
    build:
      context: labseq-ui
    ports:
      - "4200:80"
    depends_on:
      - labseq-api
    networks:
      - labseq-network

networks:
  labseq-network:


