spring:
  redis:
    host: redis
    port: 6379
  cloud:
    compatibility-verifier:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        dialect: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always